# Generated by Django 5.1.1 on 2024-10-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='profile_user_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
