# Generated by Django 5.1.1 on 2024-09-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_cadastro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
