# Generated by Django 5.1.1 on 2024-12-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.CharField(max_length=40, verbose_name='Author')),
                ('quantity_registred', models.IntegerField(verbose_name='Quantity Registred')),
                ('loan_quantity', models.IntegerField(default=0, verbose_name='Loan Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='book_category_category', to='book.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='books', verbose_name='Image')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='imagebook_book_book', to='book.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Image Book',
                'verbose_name_plural': 'Images Books',
                'ordering': ['-id'],
            },
        ),
    ]
